export const skills = [
  { title: "Javascript", value: 80, color: "blue.400" },
  { title: "ES5 & ES6", value: 80, color: "green.400" },
  { title: "Typescript", value: 80, color: "red.400" },
  { title: "React", value: 80, color: "yellow.400" },
  { title: "Nextjs", value: 80, color: "purple.400" },
  { title: "React Native", value: 60, color: "teal.400" },
  { title: "CSS", value: 80, color: "orange.400" },
  { title: "SASS", value: 80, color: "cyan.400" },
  { title: "Tailwind", value: 80, color: "pink.400" },
  { title: "RESTful API", value: 80, color: "gray.400" },
  { title: "NodeJS", value: 80, color: "blue.400" },
  { title: "ExpressJS", value: 80, color: "green.400" },
  { title: "Prisma ORM", value: 80, color: "red.400" },
  { title: "Git", value: 80, color: "yellow.400" },
  { title: "Data Structures", value: 70, color: "purple.400" },
  { title: "Design Patterns", value: 70, color: "teal.400" },
  { title: "Unit & Integration Testing", value: 80, color: "orange.400" },
  { title: "React Testing Library", value: 80, color: "cyan.400" },
  { title: "Network +", value: 80, color: "pink.400" },
  { title: "Adobe XD", value: 70, color: "gray.400" },
  { title: "SQL", value: 80, color: "blue.400" },
  { title: "noSQL", value: 80, color: "green.400" },
];
